### ISSUE TITLE
HS: Start Game Script

### ISSUE THREAD

**Issue by mmsheeks** [clovercraft/denizen#10]
## Feature

This should be called by the command documented in issue #6. When called, start the Hide & Seek match

**Sequence**

The start of the game should follow the sequence below

1. Narrate "Selecting a seeker..." then wait a couple seconds
2. Pick a random player on the server flagged `hs_active` to be the seeker
4. Narrate "You are are the seeker!" to the selected player and flag them with `hs_seeker`
5. Narrate "You are not the seeker." to players flagged `hs_active` but not flagged `hs_seeker` and flag them with `hs_hidden`
6. Using title cards, count down from 3 to 1, then show a "Match Start" title
7. Apply the "darkness" effect to the player flagged `hs_seeker` for 120 seconds
8. Narrate "You have two minutes to hide!" to all players flagged `hs_active`
9. wait 1.5 minutes
10. Narrate "30 seconds left to hide!" to all players flagged `hs_active`
11. wait 30 seconds
12. Narrate "The hunt is on!" to all players flagged `hs_active`
13. Remove the darkness effect from the player flagged `hs_seeker`
14. Flag the server with `hs_running` to indicate to world scripts that a game of Hide & Seek is running.

**Comment by danielbernard** [comment]
Added under https://github.com/clovercraft/denizen/pull/19
