### ISSUE TITLE
HS: End game voting script

### ISSUE THREAD

**Issue by mmsheeks** [clovercraft/denizen#11]
## Feature

This should be called by the command documented in issue #6. When called while a game of Hide & Seek is running, initiate a vote to end the session.

A session can only be ended when a majority of players still hiding vote to end the session

**Specification**
- Command can only be used by a player currently flagged `hs_hidden`
- When called, check if the server has the `hs_vote_end` flag
- If the flag exists, increment it by 1 and narrate "You vote to end." to the player
- If the flag doesn't exist, set it to 1.
- Check if the value of `hs_vote_end` is greater than or equal to the count of players currently flagged `hs_hidden`. (round down)
- If the condition is met, start the script to end the game and narrate "The game has been ended by a vote!" to all players flagged `hs_active`.

**Comment by danielbernard** [comment]
Added under https://github.com/clovercraft/denizen/pull/19
