### ISSUE TITLE
HS: End Game Script

### ISSUE THREAD

**Issue by mmsheeks** [clovercraft/denizen#12]
## Feature

This script can be reached when one of three conditions is met:
- A vote to end the round has passed as documented in #11 
- The maximum amount of game time has passed as described in #13 
- The seekers have successfully found all hidden players as described in #14 

The script should teleport all players to the world spawn location, and remove any active game flags other than `hs_active`.

**Sequence**

The start of the game should follow the sequence below

1. Narrate "The match of Hide & Seek has ended!" then wait a couple seconds
2. Teleport all players flagged `hs_active` to the world spawn
3. Remove the `hs_hidden` and `hs_seeker` flags from all players
4. Remove the `hs_running` and `hs_vote_end` flags from the server

**Comment by danielbernard** [comment]
Added under https://github.com/clovercraft/denizen/pull/19
