### ISSUE TITLE
HS: On Tag script

### ISSUE THREAD

**Issue by mmsheeks** [clovercraft/denizen#14]
## Feature

This script will handle the event of a seeking player tagging a hiding player. When a seeker tags a hiding player, the hiding player should be flagged as a seeker, and the game should announce that they got found.

**Specification**
This script should only run if the server is flagged `hs_running`.

When a player flagged `hs_seeker` hits a player flagged `hs_hidden`, do the following

1. Flag the player that was hit with `hs_seeker`
2. Remove the `hs_hidden` flag from the player that was hit
3. Narrate "[found player] was found by [seeking player]" to players flagged `hs_active`
4. Get a count of remaining players flagged `hs_hidden`
5. If no players are left hiding, narrate "Seekers win!" and run the end game script in #12 
6. If hiding players remain, Narrate "[hidden count] players remain" to players flagged `hs_active`

**Comment by danielbernard** [comment]
Added under https://github.com/clovercraft/denizen/pull/19
