### ISSUE TITLE
Warp glyphs should not activate when a player clicks on an interactable block, such as doors.

### ISSUE THREAD

**Issue by mmsheeks** [clovercraft/denizen#3]
**BUG**
In the [warp glyph](https://github.com/clovercraft/denizen/blob/production/modules/warp-network/items.dsc#L15) items script, we should be checking to make sure the block the player is clicking on is not interactable, and preventing glyph activation if it is.

**Current Behavior**
If a player right-clicks an interactable block (such as a door, lever, or chest) while holding a warp glyph, they consume the glyph and activate the flag.

**Desired Behavior**
If a player right-clicks an interactable block while holding a warp glyph, they should interact with the block and the glyph should remain unconsumed.

**Suggested Change**
If the player right-clicks with a warp glyph, check to see if the block they clicked is air. If it's not air, stop the script. Alternatively, we can specifically check for interactable blocks, but that will be more complicated.

**Comment by danielbernard** [comment]
I created https://github.com/DenizenScript/Denizen/pull/2447 to add the condition to the material upstream, but in the meantime we could implement a local fix.
some options:

1. check for air
```DenizenScript
custom_blocks_handler_events:
    type: world
    events:
        on player right clicks block with:warp_glyph type:air:
            - run cc_anchorstone_glyph_use
```

2. write our own is_interactable list
```DenizenScript
custom_blocks_handler_events:
    type: world
    events:
        on player right clicks block with:warp_glyph:
            - if cc_is_interactable def:<context.location.material>:
                - run cc_anchorstone_glyph_use
...
cc_is_interactable:
    type: procedure
    definitions: material
    description: Checks if the material is interactive
    script:
        - switch???
```
I'm not sure what the syntax is for something like that yet.

**Comment by mmsheeks** [comment]
I'd just go with option 1 here, simple and to the point. Once your upstream change is available in the distributed plugin we can run that.

**Comment by danielbernard** [comment]
I took the opportunity to learn more about denizenscript and made an overcomplicated solution that should be sufficiently efficient
