### ISSUE TITLE
HS: Game Command

### ISSUE THREAD

**Issue by mmsheeks** [clovercraft/denizen#6]
## Feature

Add a command to allow players to interact with the hide and seek system. Players should be able to:
- join a match (#7)
- leave a match (#9)
- start a match (#10)
- vote to end a match (#11)

Each sub-command of the parent command can be developed as an individual action script, documented in other issues on this milestone. This command simply needs to parse the user input, and call the correct command.

**Command Spec**
```
/hide-seek <action>

# <action> choices:
join - joins a match
leave - leaves a match
start - starts a match
end - start a vote to end the match, or vote yes to end
```

**Comment by danielbernard** [comment]
Added under clovercraft/denizen/pull/19
