### ISSUE TITLE
HS: Join Game Script

### ISSUE THREAD

**Issue by mmsheeks** [clovercraft/denizen#7]
## Feature

This should be called by the command documented in issue #6.

When called, flag the player as a participant in the Hide & Seek game and tell them they've joined the match. This flag should expire after 12 hours to prevent players from inadvertently ending up in matches later that they don't mean to be in.

**Specification**
- Check if the player has the `hs_active` flag first
- If they do, narrate "You're already in the match." and stop.
- If the player doesn't have the `hs_active` flag, set it to true with a 12 hour expiration.
- narrate "You have joined the Hide & Seek match!" to the player

**Comment by danielbernard** [comment]
Added under https://github.com/clovercraft/denizen/pull/19
