### ISSUE TITLE
HS: Leave Game Script

### ISSUE THREAD

**Issue by mmsheeks** [clovercraft/denizen#9]
## Feature

This should be called by the command documented in issue #6.

When called, remove the flag indicating that the player is in the Hide & Seek match. If they don't have it, just tell them that instead.

**Specification**
- Check if the player has the `hs_active` flag first
- If they do, remove the flag by setting it as `hs_active:!`
- If the player doesn't have the `hs_active` flag, narrate "You are not in a match."
- narrate "You have left the Hide & Seek match!" to the player

**Comment by danielbernard** [comment]
Added under https://github.com/clovercraft/denizen/pull/19
